do_predict: true
do_train: true

main_dir: '../parser_workdir'
output_dir: ${main_dir}/srl_parser
data_dir: ${main_dir}/data/open_sesame_v1_data/fn1.7

train_file: 'fn1.7.fulltext.train.syntaxnet.conll'
dev_file: 'fn1.7.dev.syntaxnet.conll'
test_file: 'fn1.7.test.syntaxnet.conll'
exp_dir: 'verbs'

seed: 42
model_run: ${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra:
  run:
    dir: ${output_dir}/${exp_dir}/${model_run}

model:
    model_name: 'bert-large-cased'
    model_path: ''
    use_predicate: false
    ebs: 500

data:
    train_data_path: ${data_dir}/${exp_dir}/${train_file}
    dev_data_path: ${data_dir}/${exp_dir}/${dev_file}
    test_data_path: ${data_dir}/${exp_dir}/${test_file}
    
    pred_data_path: ${data_dir}/${exp_dir}/${test_file}
    
training:
    bs: 8 # If this batch size
    lr: 2e-5
    num_epochs: 50
    train_steps: -1
    weight_decay: 0.01
    warmup_ratio: 0.1
    accum: 1
    ema_decay: 0. # Enable ema with the value 0.999
    enable_validation: true
